const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
if (!process.env.TEST_DATABASE_URL) throw new Error('Set TEST_DATABASE_URL to a dedicated disposable PostgreSQL database');
const url = new URL(process.env.TEST_DATABASE_URL);
if (!/test/i.test(url.pathname)) throw new Error('Test database name must contain test');
process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
process.env.JWT_SECRET = 'integration-test-secret';
const sentEmails = [];
require.cache[require.resolve('../src/core/utils/sendEmail')] = { exports: async (message) => sentEmails.push(message) };
const { sequelize } = require('../src/config/db');
const { User, Product, Category, Coupon, Order } = require('../src/config/models');
const { app } = require('../src/server');
test('PostgreSQL API migration', async (t) => {
  let server;
  try {
    await sequelize.sync({ force: true });
    const admin = await User.create({ name: 'Admin', email: 'admin@test.local', password: 'secret123', isAdmin: true });
    assert.equal(await admin.matchPassword('secret123'), true);
    assert.notEqual(admin.password, 'secret123');
    server = app.listen(0, '127.0.0.1');
    await new Promise((resolve) => server.once('listening', resolve));
    const base = 'http://127.0.0.1:' + server.address().port;
    const request = async (path, method = 'GET', body, token) => {
      const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
      return { status: response.status, body: await response.json() };
    };
    const login = await request('/api/users/login', 'POST', { email: admin.email, password: 'secret123' });
    assert.equal(login.status, 200); const token = login.body.token;
    assert.equal((await request('/api/users/profile', 'GET', undefined, token)).body._id, admin._id);
    const category = await request('/api/categories', 'POST', { name: 'Computers' }, token);
    assert.equal(category.status, 201);
    const product = await request('/api/products', 'POST', { name: 'Laptop 100% Test', price: 100, category: 'Computers', countInStock: 3, image: '/laptop.jpg', description: 'Test' }, token);
    assert.equal(product.status, 201); const id = product.body._id;
    assert.equal(typeof product.body.price, 'number');
    assert.equal((await request('/api/products?keyword=100%25&min=50&max=150')).body.length, 1);
    assert.equal((await request('/api/products?category=missing')).body.length, 0);
    assert.deepEqual((await request('/api/products/categories')).body, ['Computers']);
    assert.equal((await request('/api/categories/' + category.body._id)).body.products.length, 1);
    assert.equal((await request('/api/products/' + id)).status, 200);
    assert.equal((await request('/api/products/invalid')).status, 404);
    const coupon = await request('/api/coupons', 'POST', { code: 'SAVE', discount: 10, expirationDate: new Date(Date.now() + 86400000), applicableCategories: ['Computers'] }, token);
    assert.equal(coupon.status, 201);
    assert.equal((await request('/api/coupons/validate', 'POST', { code: 'save', cartItems: [{ category: 'Computers' }] })).body.discount, 10);
    const orderBody = { orderItems: [{ product: id, qty: 1, price: 1, name: 'fake' }], shippingAddress: { address: '1 Street', city: 'City', postalCode: '10000', country: 'VN' }, paymentMethod: 'COD', taxPrice: 0, shippingPrice: 0, couponCode: 'save' };
    const placed = await request('/api/orders', 'POST', orderBody, token);
    assert.equal(placed.status, 201); assert.equal(placed.body.totalPrice, 90); assert.equal(placed.body.orderItems[0].price, 100);
    assert.equal((await Product.findByPk(id)).countInStock, 2);
    const oid = placed.body._id;
    assert.equal((await request('/api/orders/' + oid, 'GET', undefined, token)).body.user.email, admin.email);
    assert.equal((await request('/api/orders', 'GET', undefined, token)).body[0].user.name, 'Admin');
    assert.equal((await request('/api/orders/myorders', 'GET', undefined, token)).body.length, 1);
    assert.equal((await request('/api/orders/' + oid + '/pay', 'PUT', {}, token)).status, 200);
    const review = await request('/api/products/' + id + '/reviews', 'POST', { rating: 5, comment: 'Good' }, token);
    assert.equal(review.status, 201);
    assert.equal((await Product.findByPk(id)).reviews.length, 1);
    assert.equal((await request('/api/products/' + id + '/reviews', 'POST', { rating: 5, comment: 'Duplicate' }, token)).status, 400);
    const stats = await request('/api/orders/stats', 'GET', undefined, token);
    assert.equal(stats.status, 200); assert.equal(stats.body.dailyOrders[0].totalSales, 90); assert.equal(stats.body.topProducts[0].totalQty, 1);
    const cancel = await Promise.all([request('/api/orders/' + oid + '/cancel', 'PUT', {}, token), request('/api/orders/' + oid + '/cancel', 'PUT', {}, token)]);
    assert.deepEqual(cancel.map((r) => r.status).sort(), [200, 400]); assert.equal((await Product.findByPk(id)).countInStock, 3);
    await Product.update({ countInStock: 1 }, { where: { _id: id } });
    const concurrent = await Promise.all([request('/api/orders', 'POST', orderBody, token), request('/api/orders', 'POST', orderBody, token)]);
    assert.deepEqual(concurrent.map((r) => r.status).sort(), [201, 400]); assert.equal((await Product.findByPk(id)).countInStock, 0);
    const rollbackProduct = await Product.create({ name: 'Rollback', user: admin._id, price: 50, category: 'Computers', countInStock: 2, image: '/x.jpg', description: 'Test' });
    const badOrder = await request('/api/orders', 'POST', { ...orderBody, orderItems: [{ product: rollbackProduct._id, qty: 1 }], shippingAddress: {} }, token);
    assert.notEqual(badOrder.status, 201); assert.equal((await Product.findByPk(rollbackProduct._id)).countInStock, 2);
    await request('/api/users/forgot-password', 'POST', { email: admin.email });
    const email = sentEmails.at(-1); const resetToken = email.html.match(/reset-password\/([a-f0-9]+)/)[1];
    assert.equal((await request('/api/users/reset-password/' + resetToken, 'PUT', { password: 'new-secret' })).status, 200);
    assert.equal((await User.findByPk(admin._id)).resetPasswordToken, null);
    assert.equal((await request('/api/users/login', 'POST', { email: admin.email, password: 'new-secret' })).status, 200);
    const list = await request('/api/users', 'GET', undefined, token); assert.equal('password' in list.body[0], false);
    console.log('Verified auth, reset password, CRUD, filters, coupons, reviews, stats, rollback, concurrent stock/cancellation');
  } finally {
    if (server) await new Promise((resolve) => server.close(resolve));
    await sequelize.close();
  }
});
